version: "3.8"
services:
  solar-miner:
    build: .
    network_mode: host
    volumes:
      - ${APP_DATA_DIR:-./data}:/app/data
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "umbrel.app-id=solar-miner"
